<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\UploadedFile;

/**
 * This is the model class for table "attachment".
 *
 * @property int $id
 * @property int|null $entity_id
 * @property int|null $entity_type
 * @property string|null $filename
 * @property int|null $status
 * @property int|null $created_at
 * @property int|null $updated_at
 */
class Attachment extends \yii\db\ActiveRecord
{
    public $file;

    const INVOICE = 1;
    const PAYMENT = 2;
    const PRODUCT = 3;
    const CUSTOMER = 4;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'attachment';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['entity_id', 'entity_type', 'status', 'created_at', 'updated_at'], 'integer'],
            [['filename'], 'string', 'max' => 100],
        ];
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['created_at', 'updated_at'],
                ],
                // если вместо метки времени UNIX используется datetime:
            ],
        ];
    }

    public static function fileInputTypeForUploaded($filename)
    {
        $estens = substr($filename, strrpos($filename, '.'));

        switch ($estens) {
            case  '.txt' :
                return 'text';

            case '.doc' :
            case '.docx' :
            case '.ppt' :
            case '.pptx' :
            case '.xls':
            case '.xlsx' :
                return 'office';

            case '.pdf':
                return 'pdf';

            case '.jpg':
            case '.jpeg':
            case '.png':
            case '.gif':
            case '.tif':
            case '.tiff':
                return 'image';

            case '.wav':
            case '.mp3':
            case '.m4a':
            case '.ogg':
            case '.flac':
            case '.wma':
            case '.aac':
            case '.gsm':
            case '.dct':
            case '.aiff':
            case '.au':
                return 'audio';

            default:
                return 'other';

        }
    }

//    public function beforeSave($insert)
//    {
//        if ($file = UploadedFile::getInstance($this,'file')) {
//            $dir = Yii::getAlias('@app') . '/web/files/';
//            if (file_exists($dir . $this->filename))
//                unlink($dir . $this->filename);
//
//            $this->filename =
//            $file->saveAs()
//        }
//        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
//    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'entity_id' => 'Entity ID',
            'entity_type' => 'Entity Type',
            'filename' => 'Filename',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }
}
